### ISSUE TITLE
Not Compatible with React19/Nextjs15/Vercel

### ISSUE THREAD

**Issue by afroguy16** [TheSGJ/nextjs-toploader#103]
### Description
Installing `nextjs-toploader` breaks Vercel deployments with Next.js 15, even when the package is not imported or used in the codebase. The error occurs during static page generation of Next.js's default error pages.

### Error Message
```
TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/vercel/path0/emu/apps/fsp-chain-demo/node_modules/react/cjs/react.production.js:489:33)
    at h (/vercel/path0/emu/apps/fsp-chain-demo/.next/server/pages/_error.js:1:6051)
    at renderWithHooks (/vercel/path0/emu/node_modules/next/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4184:18)
    at renderElement (/vercel/path0/emu/node_modules/next/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4322:14)
    at retryNode (/vercel/path0/emu/node_modules/next/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4866:16)
    at renderNodeDestructive (/vercel/path0/emu/node_modules/next/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4684:7)
    at renderNode (/vercel/path0/emu/node_modules/next/node_modules/react-dom/cjs/react-dom-server.edge.production.js:5123:14)
    at renderChildrenArray (/vercel/path0/emu/node_modules/next/node_modules/react-dom/cjs/react-dom-server.edge.production.js:5014:7)
    at retryNode (/vercel/path0/emu/node_modules/next/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4880:9)
    at renderNodeDestructive (/vercel/path0/emu/node_modules/next/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4684:7)
Export encountered an error on /_error: /404, exiting the build.
 ⨯ Static worker exited with code: 1 and signal: null
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1
```

### Environment
- Monorepo: Turborepo
- Next.js version: 15.0.2
- React version: 19 (19.0.0-rc-02c0e824-20241028)
- Deployment platform: Vercel
- Package manager: Yarn

### Steps to Reproduce
1. Setup a Turborepo monorepo
2. Create a Next.js 15 app within the monorepo
3. Add `nextjs-toploader` to the app's dependencies
4. Deploy to Vercel
5. Build fails with useContext error in error pages

### Expected Behavior
The package should not break Vercel deployments when installed, regardless of whether it's being used or not.

### Actual Behavior
The mere presence of the package in dependencies causes build failures on Vercel during static page generation.

### Additional Notes
- The error occurs even when the package is not imported anywhere in the codebase
- The error occurs even when the package is used in the codebase
- Removing the package from dependencies fixes the build

### Screenshots

<img width="1262" alt="Screenshot 2024-11-22 at 6 35 36 AM" src="https://github.com/user-attachments/assets/cde6b0b6-5b9d-4abc-ba0a-705b0ff5936f">
<img width="1235" alt="Screenshot 2024-11-22 at 6 35 29 AM" src="https://github.com/user-attachments/assets/442301ad-28b2-4f5d-a1f5-abfc313f2d5a">
<img width="1215" alt="Screenshot 2024-11-22 at 6 35 20 AM" src="https://github.com/user-attachments/assets/588b1d01-8e86-4a8f-8ec1-58da4c8bd99a">

**Comment by leeuwd** [comment]
<img width="952" alt="Image" src="https://github.com/user-attachments/assets/99ab36d8-cb03-4b92-8219-3e09ed953a45" />

Same here.
